//
//  File.swift
//  
//
//  Created by Tibor Bodecs on 2022. 02. 17..
//

import Foundation

public extension Svg {
    
    static func icon(_ name: String) -> Svg? {
        guard let icon = Icons(rawValue: name) else {
            return nil
        }
        switch icon {
        case .columns: return Svg.columns
        case .underline: return Svg.underline
        case .grid: return Svg.grid
        case .triangle: return Svg.triangle
        case .search: return Svg.search
        case .volume2: return Svg.volume2
        case .arrowUpCircle: return Svg.arrowUpCircle
        case .pauseCircle: return Svg.pauseCircle
        case .checkSquare: return Svg.checkSquare
        case .arrowDown: return Svg.arrowDown
        case .figma: return Svg.figma
        case .cornerRightUp: return Svg.cornerRightUp
        case .chevronsRight: return Svg.chevronsRight
        case .list: return Svg.list
        case .chevronsDown: return Svg.chevronsDown
        case .wind: return Svg.wind
        case .cornerUpRight: return Svg.cornerUpRight
        case .target: return Svg.target
        case .scissors: return Svg.scissors
        case .minimize2: return Svg.minimize2
        case .playCircle: return Svg.playCircle
        case .crosshair: return Svg.crosshair
        case .airplay: return Svg.airplay
        case .xOctagon: return Svg.xOctagon
        case .`repeat`: return Svg.repeat
        case .edit3: return Svg.edit3
        case .volume1: return Svg.volume1
        case .sunrise: return Svg.sunrise
        case .toggleRight: return Svg.toggleRight
        case .umbrella: return Svg.umbrella
        case .user: return Svg.user
        case .fileMinus: return Svg.fileMinus
        case .xCircle: return Svg.xCircle
        case .circle: return Svg.circle
        case .phoneMissed: return Svg.phoneMissed
        case .edit2: return Svg.edit2
        case .cornerLeftUp: return Svg.cornerLeftUp
        case .home: return Svg.home
        case .gitlab: return Svg.gitlab
        case .music: return Svg.music
        case .smartphone: return Svg.smartphone
        case .moreHorizontal: return Svg.moreHorizontal
        case .sliders: return Svg.sliders
        case .arrowUpLeft: return Svg.arrowUpLeft
        case .chevronDown: return Svg.chevronDown
        case .hexagon: return Svg.hexagon
        case .github: return Svg.github
        case .crop: return Svg.crop
        case .tag: return Svg.tag
        case .briefcase: return Svg.briefcase
        case .rotateCw: return Svg.rotateCw
        case .map: return Svg.map
        case .inbox: return Svg.inbox
        case .alignJustify: return Svg.alignJustify
        case .plusSquare: return Svg.plusSquare
        case .power: return Svg.power
        case .database: return Svg.database
        case .cameraOff: return Svg.cameraOff
        case .toggleLeft: return Svg.toggleLeft
        case .file: return Svg.file
        case .messageCircle: return Svg.messageCircle
        case .voicemail: return Svg.voicemail
        case .terminal: return Svg.terminal
        case .move: return Svg.move
        case .maximize: return Svg.maximize
        case .chevronUp: return Svg.chevronUp
        case .arrowDownLeft: return Svg.arrowDownLeft
        case .fileText: return Svg.fileText
        case .droplet: return Svg.droplet
        case .zapOff: return Svg.zapOff
        case .x: return Svg.x
        case .barChart: return Svg.barChart
        case .lock: return Svg.lock
        case .logIn: return Svg.logIn
        case .shoppingBag: return Svg.shoppingBag
        case .divide: return Svg.divide
        case .cloudDrizzle: return Svg.cloudDrizzle
        case .refreshCw: return Svg.refreshCw
        case .chevronRight: return Svg.chevronRight
        case .clipboard: return Svg.clipboard
        case .package: return Svg.package
        case .instagram: return Svg.instagram
        case .link: return Svg.link
        case .videoOff: return Svg.videoOff
        case .key: return Svg.key
        case .meh: return Svg.meh
        case .cornerDownRight: return Svg.cornerDownRight
        case .arrowRight: return Svg.arrowRight
        case .aperture: return Svg.aperture
        case .stopCircle: return Svg.stopCircle
        case .logOut: return Svg.logOut
        case .arrowLeftCircle: return Svg.arrowLeftCircle
        case .barChart2: return Svg.barChart2
        case .gitPullRequest: return Svg.gitPullRequest
        case .minimize: return Svg.minimize
        case .minusSquare: return Svg.minusSquare
        case .settings: return Svg.settings
        case .cloudSnow: return Svg.cloudSnow
        case .thumbsDown: return Svg.thumbsDown
        case .type: return Svg.type
        case .archive: return Svg.archive
        case .phoneOutgoing: return Svg.phoneOutgoing
        case .pocket: return Svg.pocket
        case .mail: return Svg.mail
        case .shield: return Svg.shield
        case .download: return Svg.download
        case .phoneForwarded: return Svg.phoneForwarded
        case .cornerRightDown: return Svg.cornerRightDown
        case .bookOpen: return Svg.bookOpen
        case .divideSquare: return Svg.divideSquare
        case .server: return Svg.server
        case .tv: return Svg.tv
        case .skipForward: return Svg.skipForward
        case .volume: return Svg.volume
        case .userPlus: return Svg.userPlus
        case .batteryCharging: return Svg.batteryCharging
        case .layers: return Svg.layers
        case .slash: return Svg.slash
        case .radio: return Svg.radio
        case .book: return Svg.book
        case .userMinus: return Svg.userMinus
        case .bell: return Svg.bell
        case .gitBranch: return Svg.gitBranch
        case .coffee: return Svg.coffee
        case .code: return Svg.code
        case .thermometer: return Svg.thermometer
        case .cast: return Svg.cast
        case .flag: return Svg.flag
        case .eyeOff: return Svg.eyeOff
        case .battery: return Svg.battery
        case .disc: return Svg.disc
        case .frown: return Svg.frown
        case .tool: return Svg.tool
        case .cpu: return Svg.cpu
        case .bold: return Svg.bold
        case .hash: return Svg.hash
        case .share2: return Svg.share2
        case .plus: return Svg.plus
        case .check: return Svg.check
        case .rotateCcw: return Svg.rotateCcw
        case .hardDrive: return Svg.hardDrive
        case .bluetooth: return Svg.bluetooth
        case .pieChart: return Svg.pieChart
        case .headphones: return Svg.headphones
        case .rss: return Svg.rss
        case .wifi: return Svg.wifi
        case .cornerUpLeft: return Svg.cornerUpLeft
        case .watch: return Svg.watch
        case .info: return Svg.info
        case .userX: return Svg.userX
        case .loader: return Svg.loader
        case .refreshCcw: return Svg.refreshCcw
        case .folderPlus: return Svg.folderPlus
        case .gitMerge: return Svg.gitMerge
        case .mic: return Svg.mic
        case .copy: return Svg.copy
        case .zoomIn: return Svg.zoomIn
        case .arrowRightCircle: return Svg.arrowRightCircle
        case .alignRight: return Svg.alignRight
        case .image: return Svg.image
        case .maximize2: return Svg.maximize2
        case .checkCircle: return Svg.checkCircle
        case .sunset: return Svg.sunset
        case .save: return Svg.save
        case .smile: return Svg.smile
        case .navigation: return Svg.navigation
        case .cloudLightning: return Svg.cloudLightning
        case .paperclip: return Svg.paperclip
        case .fastForward: return Svg.fastForward
        case .xSquare: return Svg.xSquare
        case .award: return Svg.award
        case .zoomOut: return Svg.zoomOut
        case .box: return Svg.box
        case .thumbsUp: return Svg.thumbsUp
        case .percent: return Svg.percent
        case .sidebar: return Svg.sidebar
        case .square: return Svg.square
        case .play: return Svg.play
        case .gitCommit: return Svg.gitCommit
        case .send: return Svg.send
        case .phoneCall: return Svg.phoneCall
        case .speaker: return Svg.speaker
        case .facebook: return Svg.facebook
        case .codesandbox: return Svg.codesandbox
        case .camera: return Svg.camera
        case .link2: return Svg.link2
        case .printer: return Svg.printer
        case .folderMinus: return Svg.folderMinus
        case .arrowUpRight: return Svg.arrowUpRight
        case .truck: return Svg.truck
        case .lifeBuoy: return Svg.lifeBuoy
        case .penTool: return Svg.penTool
        case .atSign: return Svg.atSign
        case .feather: return Svg.feather
        case .trash: return Svg.trash
        case .wifiOff: return Svg.wifiOff
        case .cornerLeftDown: return Svg.cornerLeftDown
        case .dollarSign: return Svg.dollarSign
        case .star: return Svg.star
        case .cloudOff: return Svg.cloudOff
        case .sun: return Svg.sun
        case .messageSquare: return Svg.messageSquare
        case .edit: return Svg.edit
        case .anchor: return Svg.anchor
        case .alertCircle: return Svg.alertCircle
        case .chevronsUp: return Svg.chevronsUp
        case .uploadCloud: return Svg.uploadCloud
        case .twitch: return Svg.twitch
        case .youtube: return Svg.youtube
        case .unlock: return Svg.unlock
        case .compass: return Svg.compass
        case .plusCircle: return Svg.plusCircle
        case .creditCard: return Svg.creditCard
        case .cloudRain: return Svg.cloudRain
        case .trash2: return Svg.trash2
        case .skipBack: return Svg.skipBack
        case .filePlus: return Svg.filePlus
        case .delete: return Svg.delete
        case .command: return Svg.command
        case .clock: return Svg.clock
        case .octagon: return Svg.octagon
        case .phone: return Svg.phone
        case .eye: return Svg.eye
        case .phoneOff: return Svg.phoneOff
        case .codepen: return Svg.codepen
        case .dribbble: return Svg.dribbble
        case .gift: return Svg.gift
        case .externalLink: return Svg.externalLink
        case .zap: return Svg.zap
        case .trello: return Svg.trello
        case .moreVertical: return Svg.moreVertical
        case .micOff: return Svg.micOff
        case .share: return Svg.share
        case .arrowUp: return Svg.arrowUp
        case .bellOff: return Svg.bellOff
        case .linkedin: return Svg.linkedin
        case .video: return Svg.video
        case .divideCircle: return Svg.divideCircle
        case .activity: return Svg.activity
        case .twitter: return Svg.twitter
        case .mapPin: return Svg.mapPin
        case .filter: return Svg.filter
        case .phoneIncoming: return Svg.phoneIncoming
        case .italic: return Svg.italic
        case .chevronsLeft: return Svg.chevronsLeft
        case .calendar: return Svg.calendar
        case .globe: return Svg.globe
        case .arrowLeft: return Svg.arrowLeft
        case .alignCenter: return Svg.alignCenter
        case .minusCircle: return Svg.minusCircle
        case .arrowDownRight: return Svg.arrowDownRight
        case .framer: return Svg.framer
        case .volumeX: return Svg.volumeX
        case .slack: return Svg.slack
        case .cloud: return Svg.cloud
        case .downloadCloud: return Svg.downloadCloud
        case .shuffle: return Svg.shuffle
        case .rewind: return Svg.rewind
        case .upload: return Svg.upload
        case .trendingDown: return Svg.trendingDown
        case .pause: return Svg.pause
        case .arrowDownCircle: return Svg.arrowDownCircle
        case .bookmark: return Svg.bookmark
        case .alertTriangle: return Svg.alertTriangle
        case .userCheck: return Svg.userCheck
        case .tablet: return Svg.tablet
        case .alertOctagon: return Svg.alertOctagon
        case .menu: return Svg.menu
        case .chrome: return Svg.chrome
        case .shoppingCart: return Svg.shoppingCart
        case .folder: return Svg.folder
        case .users: return Svg.users
        case .cornerDownLeft: return Svg.cornerDownLeft
        case .monitor: return Svg.monitor
        case .minus: return Svg.minus
        case .helpCircle: return Svg.helpCircle
        case .navigation2: return Svg.navigation2
        case .chevronLeft: return Svg.chevronLeft
        case .film: return Svg.film
        case .moon: return Svg.moon
        case .shieldOff: return Svg.shieldOff
        case .layout: return Svg.layout
        case .mousePointer: return Svg.mousePointer
        case .alignLeft: return Svg.alignLeft
        case .heart: return Svg.heart
        case .trendingUp: return Svg.trendingUp
        }
    }
}
